### ISSUE TITLE
sandbox:create resourceProfile option throwing error

### ISSUE THREAD

**Issue by kenzrad** [SalesforceCommerceCloud/sfcc-ci#211]
I am getting an error when trying to use 'resourceProfile' as an option in sfcc-ci sandbox:create. 

command:
`sfcc-ci sandbox:create -j --realm ${realm} --ttl ${timeToLive} --resourceProfile xlarge`

error:
`stderr: "error: unknown option `--resourceProfile'\n"`

https://documentation.b2c.commercecloud.salesforce.com/DOC2/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fsandboxes%2Fb2c_sandbox_resource_profiles.html

Is this option not supported using sfcc-ci, or am I missing something here?

**Comment by mjacob4813** [comment]
Facing the same issue. Sandbox api has new parameter that needs support in SFCC-CI.

  "realm": "<your realm id>",
  "ttl": 24,
  "autoScheduled": false,
  "resourceProfile": "medium",
  "settings":

**Comment by tobiaslohr** [comment]
Why are you getting this error? Reason is simply, because the CLI does not (yet) provide this option. This tool lives from contributions. If you don't contribute, it will not change. While it makes sense to point out a certain functionality is not yet available I encourage you to suggest a change through submitting a PR.

So, this is not an issue, but it is a request for a change or enhancement.
